// Tests for src/js/lifehash.js using Node's built-in test runner.
//
// The module is a browser IIFE that renders LifeHash (version2) icons as PNG
// data URLs. These tests evaluate it with WebCrypto and a btoa shim, then
// check the rendered image against reference vectors generated by the
// canonical `lifehash` JS package (AndreasGassmann/lifehash) — hashing the
// raw fingerprint bytes, the convention Sparrow's toucan library uses — plus
// a published toucan test vector, PNG structure and the presentation rules.
//
// Run with `npm test` (part of the suite) or `node --test test/lifehash.test.mjs`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash, webcrypto } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const src = readFileSync(join(root, "src/js/lifehash.js"), "utf8");

// Evaluate the IIFE with the browser globals it expects.
const load = () => {
  const btoa = (s) => Buffer.from(s, "binary").toString("base64");
  const factory = new Function("crypto", "btoa", "TextEncoder", `${src}; return hodlLifeHash;`);
  return factory(webcrypto, btoa, TextEncoder);
};

const sha256Hex = (bytes) => createHash("sha256").update(Buffer.from(bytes)).digest("hex");

// Reference vectors: SHA-256 of the raw 32x32 RGB pixels produced by the
// canonical lifehash JS implementation (version2, module_size 1) for the
// fingerprint, hashed as raw bytes (Sparrow/toucan's convention, not the
// string form lifehash.info uses). Generated once and pinned here as a
// regression oracle.
const VECTORS = [
  { input: "73c5da0a", rgb: "09da10ffd57a4f58616a5eda313d3f0c861e79b93e1b609a012f9c3530b427b5" },
  { input: "00000000", rgb: "9003d9fd366ec3aa06f54d6797485114ec00c61bf85c0efafa91bd2e40176d5b" },
  { input: "ffffffff", rgb: "e856f1b33dfd8eef83151de7407c3d4861581ce09f11f11f2dfc6b0219a1e51b" },
  { input: "b8688df1", rgb: "d44ba038c1389003c955a6f17accfb87c98fce4e8c98c9e2a44c71067b6521fe" },
];

const renderRgbFromDigest = async (lifehash, digest) => {
  const { runGameOfLife, buildFracGrid, selectGradient, renderColors, makeBitEnumerator } = lifehash._internals;
  const history = await runGameOfLife(digest);
  const entropy = makeBitEnumerator(digest);
  entropy.next();
  entropy.next();
  const gradient = selectGradient(entropy);
  const snowflake = entropy.next();
  const frac = buildFracGrid(history);
  return renderColors(frac, gradient, snowflake);
};

// The fingerprint path: hex-decoded raw bytes are hashed, as Sparrow does.
const renderRgb = async (lifehash, fingerprintHex) =>
  renderRgbFromDigest(
    lifehash,
    new Uint8Array(await webcrypto.subtle.digest("SHA-256", Uint8Array.from(Buffer.from(fingerprintHex, "hex")))),
  );

test("rendered 32x32 RGB matches the canonical LifeHash vectors", async () => {
  const lifehash = load();
  for (const { input, rgb } of VECTORS) {
    const { width, height, data } = await renderRgb(lifehash, input);
    assert.equal(width, 32, input);
    assert.equal(height, 32, input);
    assert.equal(data.length, 32 * 32 * 3, input);
    assert.equal(sha256Hex(data), rgb, `LifeHash mismatch for ${input}`);
  }
});

test("matches Sparrow's toucan implementation byte-for-byte on its published vector", async () => {
  const lifehash = load();
  // toucan's LifeHashTest: LifeHash.makeFromUTF8("Hello", VERSION2, 1, false)
  // pins these as the first 30 RGB bytes of the 32x32 image.
  const digest = new Uint8Array(await webcrypto.subtle.digest("SHA-256", new TextEncoder().encode("Hello")));
  const { width, height, data } = await renderRgbFromDigest(lifehash, digest);
  assert.equal(width, 32);
  assert.equal(height, 32);
  const toucan = [146, 126, 130, 178, 104, 92, 182, 101, 87, 202, 88, 64, 199, 89, 66, 197, 90, 69, 182, 101, 87, 180, 102, 89, 159, 117, 114, 210, 82, 54];
  assert.deepEqual([...data.subarray(0, toucan.length)], toucan);
});

test("fromFingerprint returns a well-formed PNG data URL", async () => {
  const lifehash = load();
  const url = await lifehash.fromFingerprint("73c5da0a", 3);
  assert.match(url, /^data:image\/png;base64,/);
  const png = Buffer.from(url.split(",")[1], "base64");
  assert.deepEqual([...png.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10], "PNG signature");
  // IHDR: 32x32 source at moduleSize 3 -> 96x96, 8-bit truecolour.
  assert.equal(png.readUInt32BE(16), 96, "width");
  assert.equal(png.readUInt32BE(20), 96, "height");
  assert.equal(png[24], 8, "bit depth");
  assert.equal(png[25], 2, "colour type");
});

test("fingerprint input is case-insensitive (the decoded bytes are hashed, not the string)", async () => {
  const lifehash = load();
  const lower = await lifehash.fromFingerprint("73c5da0a");
  const upper = await lifehash.fromFingerprint("73C5DA0A");
  assert.equal(lower, upper);
});

test("fromFingerprint rejects non-hex or odd-length input", async () => {
  const lifehash = load();
  await assert.rejects(() => lifehash.fromFingerprint("73c5da0g"), /hex/);
  await assert.rejects(() => lifehash.fromFingerprint("73c5da0"), /hex/);
});

test("distinct fingerprints produce distinct images", async () => {
  const lifehash = load();
  const a = await lifehash.fromFingerprint("73c5da0a");
  const b = await lifehash.fromFingerprint("b8688df1");
  assert.notEqual(a, b);
});

test("fromFingerprint is deterministic across runs", async () => {
  const lifehash = load();
  const first = await lifehash.fromFingerprint("73c5da0a");
  const second = await lifehash.fromFingerprint("73c5da0a");
  assert.equal(first, second);
});

test("fromDigest rejects a non-32-byte digest", async () => {
  const lifehash = load();
  await assert.rejects(() => lifehash.fromDigest(new Uint8Array(16)), /32 bytes/);
});
