// Tests for src/js/lifehash.js using Node's built-in test runner.
//
// The module is a browser IIFE that renders LifeHash (version2) icons as PNG
// data URLs. These tests evaluate it with WebCrypto and a btoa shim, then
// check the rendered image against reference vectors generated by the
// Blockchain Commons C++ reference — hashing the raw fingerprint bytes, the
// convention Sparrow's toucan library uses — plus the reference's exact-bit
// float32 arithmetic, a published toucan test vector, PNG structure and the
// presentation rules.
//
// Run with `npm test` (part of the suite) or `node --test test/lifehash.test.mjs`.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash, webcrypto } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const src = readFileSync(join(root, "src/js/lifehash.js"), "utf8");

// Evaluate the IIFE with the browser globals it expects.
const load = () => {
  const btoa = (s) => Buffer.from(s, "binary").toString("base64");
  const factory = new Function("crypto", "btoa", "TextEncoder", `${src}; return hodlLifeHash;`);
  return factory(webcrypto, btoa, TextEncoder);
};

const sha256Hex = (bytes) => createHash("sha256").update(Buffer.from(bytes)).digest("hex");

// Reference vectors: SHA-256 of the raw 32x32 RGB pixels produced by
// Blockchain Commons' C++ reference (bc-lifehash at
// 0444dbed5615fbc9a98163608c6499c025b7873b), make_from_data(fingerprint
// bytes, version2, module_size 1, has_alpha false) — the raw fingerprint
// bytes, Sparrow/toucan's convention, not the string form lifehash.info uses.
// Generated with the compiled reference, not with this module, and taken from
// SeedSigner's tests/test_lifehash.py (w-s-bitcoin/seedsigner PR #3). They
// cover all four gradient families, both symmetries, leading zeros, the cases
// where the `lifehash` JS package and Sparrow disagree, and the reference's
// float32 fmodf boundary artifacts (a68bbd2f, a5f29c5c), which the JS package
// does not reproduce.
const VECTORS = Object.entries({
  "12345678": "1dccda9353a9761b591cbe79be5671dff03e3ef878eaa58db5907b8cd1a3b247",
  "73c5da0a": "09da10ffd57a4f58616a5eda313d3f0c861e79b93e1b609a012f9c3530b427b5",
  "a63dbf9c": "8f0e63315f79f353e6c0d0a818ae1f7fbbdfdd2675ea2ed10863196278b13d47",
  "9a6087a6": "34d0e99e9cbb3cb71a878a683b76df7676880037c473341b814510d90d50225a",
  "00000000": "9003d9fd366ec3aa06f54d6797485114ec00c61bf85c0efafa91bd2e40176d5b",
  "ffffffff": "e856f1b33dfd8eef83151de7407c3d4861581ce09f11f11f2dfc6b0219a1e51b",
  "00000001": "3db18a8a0897081ed9c6109be8fafe3c781aa9e8d24c130e6c9ce664f908e203",
  "00000100": "ad4e249d02f7dfdf19359af05e893bd2606acd03e3319eb2f5b65b20892e13c0",
  "00010000": "5c9d3de217fbc32d7a582eac845744d4127a93c5902def38e5848db8857355b2",
  "01000000": "c17f955c023400414275228d2f346059e99762d330e4dda68b502fa843eaebe9",
  "01234567": "caac53b2836b1e74bd28746870db91cca291430e93c40ebf24f9e97746c4c613",
  "deadbeef": "cb5c61fdbab952cd54b86824291d14e36255df58c80d25f7463db369e2d1ccf6",
  "f23c1da1": "b37a3227f8b9b318e9b755779564395e26ed9bceb302e6b38c1e9522cb6536a2",
  "b73ca8ab": "0b820859ff203bcce19e43ee4f6a829587113b2cfa77b91afc3b6f79f2e28ccc",
  "b8688df1": "d44ba038c1389003c955a6f17accfb87c98fce4e8c98c9e2a44c71067b6521fe",
  "16787299": "67d88770a39debb2649660253ae1e62325409f2aa7d500439bbdff73c59d5cce",
  "14439603": "f7263c77df9bf0edf877502fac469064c7f689c6aa52a0d884d15c020833fe2e",
  "106eb272": "cfbc7d0530ddc051afa5d8d74ce0d917a2c8f3108dd73b204aea90f101fc60b2",
  "2e5cfa4f": "608076235fc3c6b3b844bfc6cfdd829b6e7f67dc5df6016c3adbeb1b9b1cdb0a",
  "e7f7c744": "bdb2768d398b8f18bdbd4d8f88b767a08890c74a2acbee705c82fd4b7b68ba8a",
  "f8bff277": "86b4fb8f709225dfe145e16e5d6c9ccddc77ca0f3a189cc2595bafb655cc0bb0",
  "0319808f": "612c11a94188bdf2f8d5723cf07a1b588dbedf66db32d3ed9fb2a36561672bd2",
  "ffa2f9de": "6533e2ae3c77da991f32cc60dde0c4b4ff4c6309345782e775b04068e757de12",
  "9671946e": "72001fffce6c86fd08f8fccc3eb786ffe5a30dd248f0822ed47bc9602d02e58d",
  "41acd1f3": "3acfbb2826d799943f9e641863ae603f7c9e8a831a54f947f970d73e6cdccbde",
  "243ef557": "c75e1a5323d380b82824b591eb00c60052ff5df8713cd734763287e6ec4ca598",
  "0bbfab27": "6c294c4012a9474fd74646ae44956b05de0f0097acfc4c8d36a4305d0e8e49fd",
  "de9c04d7": "9962279b4302ec590740d6c5c92e5672fa5551adb73584c09f0d9a6e2a5ec31c",
  "0107118e": "29e23edec1947b3012b0108cc87a3c2e21ac4b3770fd5524bbdf8a988c87f01b",
  "e3aa047b": "39c5d326ab09d98cda029cb9799b5c35bdb88ab8b7b799ee6a97cf6c5d0754d6",
  "aee2215e": "175d201e978b6b8227e77f2d59710afb0b77fcd569449251a3eedc932831b4e9",
  "a68bbd2f": "1c8f5b3a9d49d0b2e4785a040d271e8e361fc24b42e87b504b7ecf09cc211a13",
  "a5f29c5c": "4c811efc7660757cb40aacccf38f810c0dc02732eed6ee009a3cd21db95d1958",
}).map(([input, rgb]) => ({ input, rgb }));

const renderRgbFromDigest = async (lifehash, digest) => {
  const { runGameOfLife, buildFracGrid, selectGradient, renderColors, makeBitEnumerator } = lifehash._internals;
  const history = await runGameOfLife(digest);
  const entropy = makeBitEnumerator(digest);
  entropy.next();
  entropy.next();
  const gradient = selectGradient(entropy);
  const snowflake = entropy.next();
  const frac = buildFracGrid(history);
  return renderColors(frac, gradient, snowflake);
};

// The fingerprint path: hex-decoded raw bytes are hashed, as Sparrow does.
const renderRgb = async (lifehash, fingerprintHex) =>
  renderRgbFromDigest(
    lifehash,
    new Uint8Array(await webcrypto.subtle.digest("SHA-256", Uint8Array.from(Buffer.from(fingerprintHex, "hex")))),
  );

test("rendered 32x32 RGB matches the C++ reference vectors", async () => {
  const lifehash = load();
  for (const { input, rgb } of VECTORS) {
    const { width, height, data } = await renderRgb(lifehash, input);
    assert.equal(width, 32, input);
    assert.equal(height, 32, input);
    assert.equal(data.length, 32 * 32 * 3, input);
    assert.equal(sha256Hex(data), rgb, `LifeHash mismatch for ${input}`);
  }
});

// Exact-bit values from bc-lifehash at the revision above, compiled with
// -std=c++17 -O3 -ffp-contract=off (w-s-bitcoin/toucan numeric-reference.txt
// at ea3958dabb00ac203a025fe9fb1fbf4b9ba0c78f). The reference computes
// luminance with powf/sqrtf and its modulo as fmodf(fmodf(x, 1) + 1, 1), all
// in single precision; just below an integer the modulo rounds to 0.
const bits = (x) => Buffer.from(new Float64Array([x]).buffer).toString("hex");
const hexFloat = (s) => {
  const m = /^(-?)0x([01])\.?([0-9a-f]*)p([+-]\d+)$/.exec(s);
  const mantissa = parseInt(m[2] + m[3], 16) / 16 ** m[3].length;
  return (m[1] ? -1 : 1) * mantissa * 2 ** Number(m[4]);
};

test("luminance matches the C++ reference bit-for-bit", () => {
  const { luminance } = load()._internals;
  for (const [[r, g, b], expected] of [
    [["0x1.999999999999ap-4", "0x1.999999999999ap-3", "0x1.3333333333333p-2"], "0x1.01ceb2p-3"],
    [["0x1p+0", "0x1p+0", "0x1p+0"], "0x1.564cdep-1"],
    [["0x0p+0", "0x0p+0", "0x0p+0"], "0x0p+0"],
  ]) {
    const color = { r: hexFloat(r), g: hexFloat(g), b: hexFloat(b) };
    assert.equal(bits(luminance(color)), bits(hexFloat(expected)), `luminance(${r}, ${g}, ${b})`);
  }
});

test("modulo matches the C++ reference bit-for-bit, including float32 rounding to 0", () => {
  const { modulo } = load()._internals;
  for (const [value, expected] of [
    ["0x1.fffffffffffffp-1", "0x0p+0"],
    ["0x1.fffffdfc9a9adp-1", "0x0p+0"],
    ["-0x1p-2", "0x1.8p-1"],
    ["0x1.4p+0", "0x1p-2"],
  ]) {
    assert.equal(bits(modulo(hexFloat(value), 1)), bits(hexFloat(expected)), `modulo(${value}, 1)`);
  }
});

test("matches Sparrow's toucan implementation byte-for-byte on its published vector", async () => {
  const lifehash = load();
  // toucan's LifeHashTest: LifeHash.makeFromUTF8("Hello", VERSION2, 1, false)
  // pins these as the first 30 RGB bytes of the 32x32 image.
  const digest = new Uint8Array(await webcrypto.subtle.digest("SHA-256", new TextEncoder().encode("Hello")));
  const { width, height, data } = await renderRgbFromDigest(lifehash, digest);
  assert.equal(width, 32);
  assert.equal(height, 32);
  const toucan = [146, 126, 130, 178, 104, 92, 182, 101, 87, 202, 88, 64, 199, 89, 66, 197, 90, 69, 182, 101, 87, 180, 102, 89, 159, 117, 114, 210, 82, 54];
  assert.deepEqual([...data.subarray(0, toucan.length)], toucan);
});

test("fromFingerprint returns a well-formed PNG data URL", async () => {
  const lifehash = load();
  const url = await lifehash.fromFingerprint("73c5da0a", 3);
  assert.match(url, /^data:image\/png;base64,/);
  const png = Buffer.from(url.split(",")[1], "base64");
  assert.deepEqual([...png.subarray(0, 8)], [137, 80, 78, 71, 13, 10, 26, 10], "PNG signature");
  // IHDR: 32x32 source at moduleSize 3 -> 96x96, 8-bit truecolour.
  assert.equal(png.readUInt32BE(16), 96, "width");
  assert.equal(png.readUInt32BE(20), 96, "height");
  assert.equal(png[24], 8, "bit depth");
  assert.equal(png[25], 2, "colour type");
});

test("fingerprint input is case-insensitive (the decoded bytes are hashed, not the string)", async () => {
  const lifehash = load();
  const lower = await lifehash.fromFingerprint("73c5da0a");
  const upper = await lifehash.fromFingerprint("73C5DA0A");
  assert.equal(lower, upper);
});

test("fromFingerprint rejects non-hex or odd-length input", async () => {
  const lifehash = load();
  await assert.rejects(() => lifehash.fromFingerprint("73c5da0g"), /hex/);
  await assert.rejects(() => lifehash.fromFingerprint("73c5da0"), /hex/);
});

test("distinct fingerprints produce distinct images", async () => {
  const lifehash = load();
  const a = await lifehash.fromFingerprint("73c5da0a");
  const b = await lifehash.fromFingerprint("b8688df1");
  assert.notEqual(a, b);
});

test("fromFingerprint is deterministic across runs", async () => {
  const lifehash = load();
  const first = await lifehash.fromFingerprint("73c5da0a");
  const second = await lifehash.fromFingerprint("73c5da0a");
  assert.equal(first, second);
});

test("fromDigest rejects a non-32-byte digest", async () => {
  const lifehash = load();
  await assert.rejects(() => lifehash.fromDigest(new Uint8Array(16)), /32 bytes/);
});
