// LifeHash differential fuzzer: EntropyLab's src/js/lifehash.js vs the
// official `lifehash` package (AndreasGassmann/lifehash, pinned in
// fuzzing/package.json).
//
// Every input goes through both full public pipelines and the rendered pixels
// must be byte-identical:
//   ours:    fromFingerprint(fp, moduleSize) -> PNG data URL -> decoded RGB
//   theirs:  LifeHash.makeFrom(hexToBytes(fp), version2, moduleSize, false).colors
// Both hash the RAW fingerprint bytes (Sparrow/toucan's convention), so the
// fuzzer also guards that the app stays Sparrow-compatible.
//
// The app follows the Blockchain Commons C++ reference's single-precision
// colour arithmetic (fmodf modulo, powf/sqrtf luminance), which the package
// computes in double precision; the two disagree on roughly 1% of
// fingerprints. "theirs" is therefore the pinned package with exactly those
// two functions swapped for the C++ semantics (see loadReferencePackage), so
// the fuzzer keeps checking everything else — hashing, the Game of Life, bit
// reading, gradient selection, symmetry, PNG encoding and scaling. The float32
// arithmetic itself is pinned by C++ reference vectors, here (VECTORS, which
// the substituted package must also reproduce) and in test/lifehash.test.mjs,
// and fuzzed against the compiled reference by fuzz-cpp.mjs. Comparing the
// app's final PNG (rather than internals) also covers the hand-rolled PNG
// encoder and the module-size scaling.
//
// Deterministic: inputs come from a seeded xorshift64 PRNG, so a CI failure
// reproduces locally with the same FUZZ_SEED (and FUZZ_ITERATIONS). The app
// never sees this randomness — the harness only feeds it test inputs, which
// is policy-safe (deterministic transformations, no key material).
//
// Run: npm --prefix fuzzing run fuzz:lifehash
//      FUZZ_ITERATIONS=5000 FUZZ_SEED=0x1234 node fuzzing/lifehash/fuzz.mjs
import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  ITERATIONS, MODULE_SIZES, SEED, decodePngRgb, firstDifference, hexToBytes, nextFingerprint, ours, sha256Hex,
} from "./common.mjs";

// Copy the pinned package to a scratch directory and substitute the C++
// reference's float32 modulo and luminance. Each replacement must match the
// package source exactly once, so a package change fails here, loudly.
const loadReferencePackage = async () => {
  const pkg = dirname(createRequire(import.meta.url).resolve("lifehash/package.json"));
  // Beside the package in node_modules, so its own dependencies still resolve.
  const dir = mkdtempSync(join(dirname(pkg), ".lifehash-ref-"));
  try {
    cpSync(pkg, dir, { recursive: true });
    const patch = (file, from, to) => {
      const path = join(dir, "src/lifehash", file);
      const text = readFileSync(path, "utf8");
      if (text.split(from).length !== 2) throw new Error(`lifehash package changed: ${file} no longer matches the float32 patch`);
      writeFileSync(path, text.replace(from, to));
    };
    patch(
      "math-utils.js",
      "return ((dividend % divisor) + divisor) % divisor;",
      "const f = Math.fround; return f(f(f(dividend) % f(divisor)) + f(divisor)) % f(divisor);",
    );
    patch(
      "Color.js",
      `return Math.sqrt(Math.pow(0.299 * this.r, 2) +
            Math.pow(0.587 * this.g, 2) +
            Math.pow(0.114 * this.b, 2));`,
      `const f = Math.fround, sq = (x) => f(f(x) * f(x));
        return f(Math.sqrt(f(f(sq(0.299 * this.r) + sq(0.587 * this.g)) + sq(0.114 * this.b))));`,
    );
    return await import(pathToFileURL(join(dir, "src/index.js")).href);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
};
const { LifeHash, LifeHashVersion } = await loadReferencePackage();

// Non-vacuity guard: a subset of the vectors test/lifehash.test.mjs pins,
// generated by the C++ reference over the raw fingerprint bytes (Sparrow's
// convention). Both sides must reproduce them before any fuzzing happens — a
// fuzzer whose comparisons silently no-op must fail here, loudly. The last
// three are cases the unpatched package gets wrong, so they also prove the
// float32 substitution took effect.
const VECTORS = [
  { input: "73c5da0a", rgb: "09da10ffd57a4f58616a5eda313d3f0c861e79b93e1b609a012f9c3530b427b5" },
  { input: "00000000", rgb: "9003d9fd366ec3aa06f54d6797485114ec00c61bf85c0efafa91bd2e40176d5b" },
  { input: "ffffffff", rgb: "e856f1b33dfd8eef83151de7407c3d4861581ce09f11f11f2dfc6b0219a1e51b" },
  { input: "b8688df1", rgb: "d44ba038c1389003c955a6f17accfb87c98fce4e8c98c9e2a44c71067b6521fe" },
  { input: "e3aa047b", rgb: "39c5d326ab09d98cda029cb9799b5c35bdb88ab8b7b799ee6a97cf6c5d0754d6" },
  { input: "a68bbd2f", rgb: "1c8f5b3a9d49d0b2e4785a040d271e8e361fc24b42e87b504b7ecf09cc211a13" },
  { input: "a5f29c5c", rgb: "4c811efc7660757cb40aacccf38f810c0dc02732eed6ee009a3cd21db95d1958" },
];
// Edge inputs beyond the PRNG stream: boundary nibbles, repeated bytes, and
// uppercase variants (hex decoding is case-insensitive on both sides, so
// ours(UPPER) is compared against theirs(lower)).
const FIXED = [
  "00000000", "ffffffff", "01234567", "89abcdef", "deadbeef", "aaaaaaaa", "55555555", "0f0f0f0f", "f0f0f0f0",
  ...VECTORS.map((v) => v.input.toUpperCase()),
];

let comparisons = 0;
const fail = (fingerprint, moduleSize, message) => {
  process.stderr.write(
    `LifeHash mismatch: fingerprint=${fingerprint} moduleSize=${moduleSize} ` +
    `seed=0x${SEED.toString(16)} iterations=${ITERATIONS}\n  ${message}\n`,
  );
  process.exit(1);
};

const compare = async (fingerprint, moduleSize, theirsFp = fingerprint) => {
  const oursPng = decodePngRgb(await ours.fromFingerprint(fingerprint, moduleSize));
  const theirs = LifeHash.makeFrom(hexToBytes(theirsFp), LifeHashVersion.version2, moduleSize, false);
  const difference = firstDifference(oursPng, theirs.width, theirs.height, Uint8Array.from(theirs.colors));
  if (difference) fail(fingerprint, moduleSize, difference);
  comparisons += 1;
  return oursPng;
};

// 1. Pinned-vector guard on both sides (module size 1, raw 32x32 RGB).
for (const { input, rgb } of VECTORS) {
  const oursPng = await compare(input, 1);
  if (sha256Hex(oursPng.rgb) !== rgb) fail(input, 1, "EntropyLab no longer reproduces the pinned C++ reference vector");
  const theirs = LifeHash.makeFrom(hexToBytes(input), LifeHashVersion.version2, 1, false);
  if (sha256Hex(theirs.colors) !== rgb) fail(input, 1, "the float32-patched `lifehash` package no longer reproduces the C++ reference vector");
}

// 2. Fixed edge inputs, at every module size; uppercase variants compare
// against the lowercased reference input.
for (const fingerprint of FIXED) {
  const lower = fingerprint.toLowerCase();
  for (const moduleSize of MODULE_SIZES) await compare(fingerprint, moduleSize, lower);
}

// 3. The PRNG stream.
for (let i = 0; i < ITERATIONS; i += 1) {
  const fingerprint = nextFingerprint();
  for (const moduleSize of MODULE_SIZES) await compare(fingerprint, moduleSize);
}

process.stdout.write(
  `LifeHash fuzz OK: ${comparisons} comparisons ` +
  `(${FIXED.length} fixed + ${ITERATIONS} PRNG inputs x ${MODULE_SIZES.length} module sizes, ` +
  `seed=0x${SEED.toString(16)}), 0 mismatches\n`,
);
