// Shared loader for the EntropyLab WebAssembly module: libsecp256k1 and
// bitcoin_hashes compiled to WebAssembly (Rust crate in entropylab-wasm/,
// artifact generated by scripts/build-wasm.mjs into entropylab-wasm-b64.js).
//
// Every facade that talks to the WASM (secp256k1.js, hashes.js, ...) imports
// the helpers here so the module is decoded and instantiated exactly once.
// The boundary helpers copy inputs into linear memory for the duration of
// one call and copy outputs back out; el_free zeroes each buffer before
// deallocating it. Buffers are not the only copies, though: Rust frames
// (including dependency code with no erase API) spill arguments and
// temporaries into the shadow stack, which also lives in linear memory and is
// not erased when a frame pops. So every export is wrapped to schedule a
// zeroing of the whole stack region once per task (wasm-stack-scrub.js).
//
// Loading: browsers refuse to compile a module this size synchronously on
// the main thread, so in the browser instantiation is async and app boot
// waits on wasmReady. Node (the test suite) has no such limit, so there the
// module is initialized synchronously at import time.
import { ENTROPYLAB_WASM_B64 } from "./entropylab-wasm-b64.js";
import { makeStackScrub, stackRegion } from "./wasm-stack-scrub.js";

export { stackRegion };

// A key worker (ln-worker.js) is bundled without the base64 module and gets
// the page's bytes in its first message, set here before this runs.
const injectedBytes = globalThis.__entropyLabWasmBytes instanceof ArrayBuffer ? new Uint8Array(globalThis.__entropyLabWasmBytes) : null;
const wasmBytes = injectedBytes ?? (() => {
  const binary = atob(ENTROPYLAB_WASM_B64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();
// A copy of the module bytes (public) for a key worker to instantiate its own
// instance, with its own linear memory, from.
export const wasmModuleBytes = () => wasmBytes.slice();

// The shadow-stack region is verified against the binary at load and the
// exports are wrapped to zero that region once per task; see
// wasm-stack-scrub.js for the mechanism and its failure modes.
const stack = makeStackScrub(wasmBytes);
export const wasmStackTop = () => stack.stackTop;
// Exported for the tests that fill the region to watch the scrub. Callers
// that need the stack clean synchronously call scrubStack().
export const scrubStack = () => stack.scrubStack();

let wasm = null; // Wrapped WebAssembly exports; set by init below.

const bind = (instance) => {
  stack.bind(instance);
  wasm = stack.guard(instance.exports);
};

const isNode = typeof process !== "undefined" && !!(process.versions && process.versions.node);
// Node has no synchronous-compilation size limit, so tests stay synchronous;
// neither has a worker, so a key worker is ready before its first message.
const syncInit = isNode || injectedBytes !== null;
if (syncInit) {
  bind(new WebAssembly.Instance(new WebAssembly.Module(wasmBytes), {}));
}
export const wasmReady = syncInit
  ? Promise.resolve()
  : WebAssembly.instantiate(wasmBytes, {}).then(({ instance }) => bind(instance));

export const requireReady = () => {
  if (!wasm) throw new Error("EntropyLab WebAssembly is not initialized yet; await wasmReady.");
};
export const wasmExports = () => {
  requireReady();
  return wasm;
};
// The WASM heap can grow during a call, detaching earlier views; take a fresh
// view of the whole buffer whenever memory is touched.
export const heap = () => new Uint8Array(wasmExports().memory.buffer);
// Copies `input` into WASM memory for the duration of `fn(pointer)`.
export const withInput = (input, fn) => {
  const wasm = wasmExports();
  const ptr = wasm.el_alloc(input.length);
  heap().set(input, ptr);
  try {
    return fn(ptr);
  } finally {
    wasm.el_free(ptr, input.length);
  }
};
// Runs `fn(outPointer)`, returning the bytes the call produced, or null when
// the call reports an error (a negative length).
export const withOutput = (capacity, fn) => {
  const wasm = wasmExports();
  const ptr = wasm.el_alloc(capacity);
  try {
    const length = fn(ptr);
    return length < 0 ? null : heap().slice(ptr, ptr + length);
  } finally {
    wasm.el_free(ptr, capacity);
  }
};
