// PSBT (BIP-174) inspection and re-serialization for EntropyLab, backed by
// rust-bitcoin 0.32.102 compiled to WebAssembly (Rust crate in psbt-wasm/,
// artifact generated by scripts/build-wasm.mjs into psbt-wasm-b64.js).
//
// Three functions cross the boundary, all over the same two-call convention
// (null output pointer reports the required capacity):
//
//   psbtInspectDoc(bytes) -> structured document describing the unsigned
//     transaction, every key-value pair of every map (typed decode for known
//     BIP-174/BIP-371 keys, raw hex for unknown ones), totals and fee,
//     rust-bitcoin's own parse verdict, and single-file payjoin signals.
//   psbtBuildBytes(doc)   -> PSBT bytes, after rust-bitcoin's
//     Psbt::deserialize has accepted the rebuilt file.
//   psbtPayjoinCompare({ original, proposal, paymentScript })
//     -> BIP-78/77 sender-checklist report for an Original PSBT and a
//     Payjoin Proposal. paymentScript is optional (hex of the BIP-21
//     payment output). No network, no randomness.
//
// Nothing here holds keys or generates randomness; the module only ever sees
// PSBT bytes and UTF-8 JSON. Loading mirrors secp256k1.js: browsers compile
// asynchronously (app boot waits on psbtWasmReady), Node initializes
// synchronously at import time so the test suite stays synchronous.
import { PSBT_WASM_B64 } from "./psbt-wasm-b64.js";

const wasmBytes = (() => {
  const binary = atob(PSBT_WASM_B64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
})();

let wasm = null; // WebAssembly exports; set by init below.

const isNode = typeof process !== "undefined" && !!(process.versions && process.versions.node);
if (isNode) {
  // Node has no synchronous-compilation size limit; tests stay synchronous.
  wasm = new WebAssembly.Instance(new WebAssembly.Module(wasmBytes), {}).exports;
}
export const psbtWasmReady = isNode
  ? Promise.resolve()
  : WebAssembly.instantiate(wasmBytes, {}).then(({ instance }) => {
      wasm = instance.exports;
    });

const requireReady = () => {
  if (!wasm) throw new Error("PSBT WebAssembly is not initialized yet; await psbtWasmReady.");
};
// The WASM heap can grow during a call, detaching earlier views; take a fresh
// view of the whole buffer whenever memory is touched.
const heap = () => new Uint8Array(wasm.memory.buffer);

const encoder = new TextEncoder();
const decoder = new TextDecoder();

const lastError = () => {
  const needed = wasm.psbt_last_error(0, 0);
  if (needed <= 0) return "unknown PSBT WASM error";
  const ptr = wasm.psbt_alloc(needed);
  try {
    const length = wasm.psbt_last_error(ptr, needed);
    return length > 0 ? decoder.decode(heap().slice(ptr, ptr + length)) : "unknown PSBT WASM error";
  } finally {
    wasm.psbt_free(ptr, needed);
  }
};

// Copies `input` into WASM memory, runs `fn(inPtr, inLen, outPtr, outCap)`
// with the two-call capacity convention, and returns the produced bytes.
const call = (input, fn) => {
  requireReady();
  const inPtr = wasm.psbt_alloc(input.length);
  heap().set(input, inPtr);
  try {
    const needed = fn(inPtr, input.length, 0, 0);
    if (needed < 0) throw new Error(lastError());
    const outPtr = wasm.psbt_alloc(needed);
    try {
      const length = fn(inPtr, input.length, outPtr, needed);
      if (length < 0) throw new Error(lastError());
      return heap().slice(outPtr, outPtr + length);
    } finally {
      wasm.psbt_free(outPtr, needed);
    }
  } finally {
    wasm.psbt_free(inPtr, input.length);
  }
};

// Parses a PSBT (raw bytes) into the editor document. Throws on malformed
// input; the error message comes from the Rust side.
export const psbtInspectDoc = (bytes) => {
  if (!(bytes instanceof Uint8Array) || !bytes.length) throw new Error("PSBT must be a non-empty byte array.");
  return JSON.parse(decoder.decode(call(bytes, wasm.psbt_inspect)));
};

// Rebuilds PSBT bytes from a (possibly edited) editor document. Throws when
// the result would not parse as a PSBT under rust-bitcoin — and, unless
// `insane` is set, when the document fails the consensus layer (transaction
// sanity, UTXO claims, final scripts) listed in the inspect document's
// `problems`. Insane mode skips that layer only: structural PSBT validity is
// still enforced, so the output is always a parseable PSBT.
export const psbtBuildBytes = (doc, { insane = false } = {}) => {
  if (!doc || typeof doc !== "object") throw new Error("editor document must be an object.");
  return call(encoder.encode(JSON.stringify(insane ? { ...doc, insane: true } : doc)), wasm.psbt_build);
};

const bytesToHex = (bytes) => [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");

// Original PSBT vs Payjoin Proposal. `original` and `proposal` are raw
// PSBT bytes. `paymentScript` is optional scriptPubKey bytes for the
// BIP-21 payment output; omit it to leave a lone substitution unconfirmed.
export const psbtPayjoinCompare = ({ original, proposal, paymentScript = null } = {}) => {
  if (!(original instanceof Uint8Array) || !original.length) throw new Error("original PSBT must be a non-empty byte array.");
  if (!(proposal instanceof Uint8Array) || !proposal.length) throw new Error("proposal PSBT must be a non-empty byte array.");
  if (paymentScript != null && (!(paymentScript instanceof Uint8Array) || !paymentScript.length)) {
    throw new Error("payment script must be a non-empty byte array when supplied.");
  }
  const request = {
    original: bytesToHex(original),
    proposal: bytesToHex(proposal),
    paymentScript: paymentScript ? bytesToHex(paymentScript) : null,
  };
  return JSON.parse(decoder.decode(call(encoder.encode(JSON.stringify(request)), wasm.psbt_payjoin_compare)));
};
