// secp256k1 operations for EntropyLab, backed by libsecp256k1 compiled to
// WebAssembly (Rust crate in entropylab-wasm/, artifact generated by
// scripts/build-wasm.mjs into entropylab-wasm-b64.js, loaded by
// entropylab-wasm.js).
//
// Drop-in replacement for the slice of @noble/curves/secp256k1.js the app
// uses: getPublicKey, sign, verify, Signature (strict DER <-> compact), and
// Point (parse/serialize/add/multiply). Nothing here generates randomness:
// sign() is RFC 6979 and rejects extraEntropy: true on purpose.
//
// Loading: browsers compile the WASM asynchronously and app boot waits on
// secp256k1Ready; Node (the test suite) initializes synchronously at import
// time. See entropylab-wasm.js.
import { heap, requireReady, wasmExports, wasmReady, withInput, withOutput } from "./entropylab-wasm.js";

export const secp256k1Ready = wasmReady;

const ORDER = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141n;
const ORDER_HALF = ORDER >> 1n;
// The generator point, compressed. Fixed published constant (SEC 2; also the
// BIP-340 generator).
const GENERATOR_COMPRESSED = "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798";

const hexToBytes = (hex) => {
  if (typeof hex !== "string" || hex.length % 2 || /[^0-9a-f]/i.test(hex)) throw new Error("Invalid hexadecimal input.");
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
};
const bytesToHex = (bytes) => [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
const bigToBytes32 = (value) => {
  if (value <= 0n || value >= ORDER) throw new Error("Scalar is out of the secp256k1 range.");
  const hex = value.toString(16).padStart(64, "0");
  return hexToBytes(hex);
};
const bytesToBig = (bytes) => BigInt("0x" + bytesToHex(bytes));

// ── WASM boundary ──────────────────────────────────────────────────────────
// Shared with the other facades in entropylab-wasm.js: withInput copies into
// linear memory for one call, withOutput copies the produced bytes back out.
const wasm = () => wasmExports();

const assertBytes32 = (bytes, what) => {
  if (!(bytes instanceof Uint8Array) || bytes.length !== 32) throw new Error(`${what} must be 32 bytes.`);
};

// ── ECDSA signature encodings ───────────────────────────────────────────────
// Strict DER, matching noble's rules: exact length, minimal integer padding,
// no negative integers, r and s in [1, n-1]. Anything else throws.

const derDecode = (bytes) => {
  const fail = () => {
    throw new Error("Invalid DER-encoded ECDSA signature.");
  };
  if (!(bytes instanceof Uint8Array) || bytes.length < 8 || bytes[0] !== 0x30 || bytes[1] !== bytes.length - 2) fail();
  const readInt = (offset) => {
    if (bytes[offset] !== 0x02) fail();
    const len = bytes[offset + 1];
    if (len < 1 || len > 33 || offset + 2 + len > bytes.length) fail();
    const int = bytes.slice(offset + 2, offset + 2 + len);
    if (int[0] & 0x80) fail(); // negative
    if (len > 1 && int[0] === 0x00 && !(int[1] & 0x80)) fail(); // non-minimal
    if (len === 33 && (int[0] !== 0x00 || !(int[1] & 0x80))) fail(); // bad padding
    return { value: int.length === 33 ? int.slice(1) : int, next: offset + 2 + len };
  };
  const r = readInt(2);
  const s = readInt(r.next);
  if (s.next !== bytes.length) fail();
  const compact = new Uint8Array(64);
  compact.set(r.value, 32 - r.value.length);
  compact.set(s.value, 64 - s.value.length);
  return compact;
};

const derEncode = (compact) => {
  const encodeInt = (bytes) => {
    let start = 0;
    while (start < 31 && bytes[start] === 0 && !(bytes[start + 1] & 0x80)) start++;
    const trimmed = bytes.slice(start);
    const padded = trimmed[0] & 0x80 ? new Uint8Array([0, ...trimmed]) : trimmed;
    return new Uint8Array([0x02, padded.length, ...padded]);
  };
  const r = encodeInt(compact.slice(0, 32));
  const s = encodeInt(compact.slice(32, 64));
  return new Uint8Array([0x30, r.length + s.length, ...r, ...s]);
};

const checkRange = (compact) => {
  const r = bytesToBig(compact.slice(0, 32));
  const s = bytesToBig(compact.slice(32, 64));
  if (r === 0n || r >= ORDER || s === 0n || s >= ORDER) throw new Error("Signature r/s out of the secp256k1 range.");
};

class Signature {
  #compact;
  constructor(compact) {
    checkRange(compact);
    this.#compact = compact;
  }
  static fromBytes(bytes, format = "compact") {
    if (format === "der") return new Signature(derDecode(bytes));
    if (format !== "compact" || !(bytes instanceof Uint8Array) || bytes.length !== 64) {
      throw new Error("Invalid compact ECDSA signature; expected 64 bytes.");
    }
    return new Signature(bytes.slice());
  }
  toBytes(format = "compact") {
    if (format === "der") return derEncode(this.#compact);
    return this.#compact.slice();
  }
}

// ── Curve points ────────────────────────────────────────────────────────────
// A Point is stored as its compressed 33-byte encoding and re-parsed by the
// WASM on each operation, keeping the JS side free of curve internals.

class Point {
  #compressed;
  constructor(compressed) {
    this.#compressed = compressed;
  }
  static get BASE() {
    return Point.fromHex(GENERATOR_COMPRESSED);
  }
  static fromBytes(bytes) {
    requireReady();
    const normalized = withInput(bytes, (p) => withOutput(65, (out) => wasm().secp_point_parse_serialize(p, bytes.length, out, 1)));
    if (!normalized) throw new Error("Invalid public key encoding: not a secp256k1 point.");
    return new Point(normalized);
  }
  static fromHex(hex) {
    return Point.fromBytes(hexToBytes(hex));
  }
  toBytes(compressed = true) {
    if (compressed) return this.#compressed.slice();
    requireReady();
    return withInput(this.#compressed, (p) => withOutput(65, (out) => wasm().secp_point_parse_serialize(p, 33, out, 0)));
  }
  add(other) {
    requireReady();
    const sum = withInput(this.#compressed, (a) =>
      withInput(other.#compressed, (b) => withOutput(65, (out) => wasm().secp_point_add(a, 33, b, 33, out)))
    );
    if (!sum) throw new Error("Point addition failed (point at infinity).");
    return new Point(sum);
  }
  multiply(scalar) {
    requireReady();
    const product = withInput(this.#compressed, (p) =>
      withInput(bigToBytes32(scalar), (s) => withOutput(65, (out) => wasm().secp_point_mul(p, 33, s, out, 1)))
    );
    // noble returns the point at infinity for a zero or curve-order scalar;
    // libsecp256k1 rejects the tweak. Callers here pre-validate the scalar.
    if (!product) throw new Error("Point multiplication failed.");
    return new Point(product);
  }
}

// ── Public API (the noble/curves surface the app uses) ─────────────────────

const getPublicKey = (privateKey, compressed = true) => {
  requireReady();
  assertBytes32(privateKey, "Private key");
  const pubkey = withInput(privateKey, (p) => withOutput(65, (out) => wasm().secp_pubkey_create(p, out, compressed ? 1 : 0)));
  if (!pubkey) throw new Error("Invalid secp256k1 private key.");
  return pubkey;
};

const sign = (msghash, privateKey, options = {}) => {
  requireReady();
  if (options.prehash !== false) throw new Error("Only pre-hashed 32-byte messages are supported (prehash: false).");
  assertBytes32(msghash, "Message hash");
  assertBytes32(privateKey, "Private key");
  const extra = options.extraEntropy;
  // extraEntropy: true would pull from a CSPRNG. EntropyLab never invents
  // entropy, so only `false`/absent (plain RFC 6979) or an explicit,
  // caller-supplied 32-byte value (Bitcoin Core-style low-r grinding) is
  // accepted.
  if (extra === undefined || extra === false || extra === null) {
    return withInput(msghash, (m) =>
      withInput(privateKey, (k) => withOutput(64, (out) => wasm().secp_sign(m, k, 0, out)))
    ) ?? failSign();
  }
  if (!(extra instanceof Uint8Array) || extra.length !== 32) {
    throw new Error("extraEntropy must be false or a caller-supplied 32-byte array; random extra entropy is not supported.");
  }
  return withInput(msghash, (m) =>
    withInput(privateKey, (k) => withInput(extra, (e) => withOutput(64, (out) => wasm().secp_sign(m, k, e, out))))
  ) ?? failSign();
};
const failSign = () => {
  throw new Error("ECDSA signing failed: invalid private key.");
};

const verify = (signature, msghash, publicKey, options = {}) => {
  requireReady();
  try {
    if (options.prehash !== false) throw new Error("Only pre-hashed 32-byte messages are supported (prehash: false).");
    assertBytes32(msghash, "Message hash");
    const compact = Signature.fromBytes(signature, options.format || "compact").toBytes("compact");
    const highS = bytesToBig(compact.slice(32, 64)) > ORDER_HALF;
    if (options.lowS !== false && highS) return false;
    // libsecp256k1 rejects high-S at verify time; with lowS: false, verify a
    // normalized copy so malleated-but-valid signatures verify as they did
    // under noble.
    const effective =
      options.lowS === false && highS
        ? withInput(compact, (p) => {
            wasm().secp_sig_normalize(p);
            return heap().slice(p, p + 64);
          })
        : compact;
    return withInput(msghash, (m) =>
      withInput(publicKey, (k) => withInput(effective, (s) => wasm().secp_verify(m, k, publicKey.length, s)))
    ) === 1;
  } catch {
    return false; // noble's verify never throws on malformed signatures/keys.
  }
};

export const secp256k1 = { getPublicKey, sign, verify, Signature, Point };
