// Verifies the freshly built site artifact: the compiled entropylab.html and
// the published assets. The artifact is generated by `npm run build` (CI
// downloads the single tested candidate — with a digest check — before
// running this, rather than rebuilding it); the tested candidate is committed
// back to rock by the artifact job after each merge.
// Zero dependencies. Run with `npm run verify`.
import {
  existsSync,
  lstatSync,
  readdirSync,
  readFileSync,
  statSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const fail = (message) => {
  console.error(message);
  process.exit(1);
};

const repoDir = dirname(dirname(fileURLToPath(import.meta.url)));
const pkg = JSON.parse(readFileSync(join(repoDir, "package.json"), "utf8"));
const version = pkg.version;

if (!/^\d+(?:\.\d+)*$/.test(version)) {
  fail(`Invalid version in package.json: ${version}`);
}
const appFile = "entropylab.html";
const workerFile = "service-worker.js";

for (const name of [appFile, "manifest.webmanifest", "service-worker.js", "assets/favicon.png", "assets/entropylab-darkmode.png", "assets/pwa-icon-180.png", "assets/pwa-icon-192.png", "assets/pwa-icon-512.png"]) {
  const path = join(repoDir, name);
  if (!existsSync(path) || statSync(path).size === 0) {
    fail(`Site artifact is missing or empty: ${name}\nRun 'npm run build' first.`);
  }
}

// No stale versioned snapshots at the repository root.
const rootSnapshots = readdirSync(repoDir).filter((name) => /^entropylab-\d+(?:\.\d+)*\.html$/.test(name));
if (rootSnapshots.length !== 0) {
  fail(`Unexpected versioned snapshots at the root: ${rootSnapshots.join(", ")}`);
}

// Published assets must be intact and free of symbolic links.
const walk = (dir, prefix) => {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const label = join(prefix, name);
    const stats = lstatSync(path);
    if (stats.isSymbolicLink()) fail(`Symbolic link in published assets: ${label}`);
    if (stats.isDirectory()) {
      walk(path, label);
    } else if (stats.size === 0) {
      fail(`Empty published asset: ${label}`);
    }
  }
};
walk(join(repoDir, "assets"), "assets");

// The built page and worker must identify the same immutable cache candidate.
// A mismatch could leave an installed iPhone app serving stale wallet code.
const html = readFileSync(join(repoDir, appFile), "utf8");
const worker = readFileSync(join(repoDir, workerFile), "utf8");
const htmlPwaVersion = html.match(/service-worker\.js\?v=([0-9a-f]{16})/i)?.[1];
const workerPwaVersion = worker.match(/const VERSION = "([0-9a-f]{16})"/)?.[1];
if (!htmlPwaVersion || htmlPwaVersion !== workerPwaVersion) {
  fail("Generated HTML and service worker do not share the same PWA version.");
}
if (html.includes("{{PWA_VERSION}}") || worker.includes("{{PWA_VERSION}}")) {
  fail("Unresolved PWA version token in generated site artifact.");
}

console.log(`Verified site artifact for v${version} (${appFile}, assets/).`);
